### ISSUE TITLE
Problem on win32 XP SP3 x86

### ISSUE THREAD

**Issue by fithisux** [sourcemint/sm-npm#1]
Hi,

I have installed nodejs 0.6.15 and the npm installation fails. I include my steps (any further clarification is welcome). I also have problem under my OpenSuse 12.1 x86_64 (similar)

D:\winoss\langs\nodejs>set PATH=%PATH%;d:\winoss\langs\nodejs;d:\winoss\langs\no
dejs\mynpm

D:\winoss\langs\nodejs>set HOME=d:\winoss\langs\nodejs

D:\winoss\langs\nodejs>npm install -g sm
npm WARN Cannot set prefix in globalconfig file
npm http GET https://registry.npmjs.org/sm
npm http 304 https://registry.npmjs.org/sm
npm http GET https://registry.npmjs.org/sourcemint-util-js/0.1.24
npm http GET https://registry.npmjs.org/sourcemint-pm-sm/0.1.23
npm http GET https://registry.npmjs.org/sourcemint-pinf-js/0.1.6
npm http 304 https://registry.npmjs.org/sourcemint-util-js/0.1.24
npm http 304 https://registry.npmjs.org/sourcemint-pm-sm/0.1.23
npm http 304 https://registry.npmjs.org/sourcemint-pinf-js/0.1.6
npm http GET https://registry.npmjs.org/wrench/1.3.8
npm http GET https://registry.npmjs.org/q/0.8.2
npm http GET https://registry.npmjs.org/glob/3.1.9
npm http GET https://registry.npmjs.org/n-util/0.0.1
npm http GET https://registry.npmjs.org/sourcemint-pm-url/0.1.1
npm http GET https://registry.npmjs.org/semver/1.0.13
npm http GET https://registry.npmjs.org/sourcemint-pm-npm/0.1.15
npm http GET https://registry.npmjs.org/sourcemint-pm-zip/0.1.1
npm http GET https://registry.npmjs.org/sourcemint-pm-tar/0.1.5
npm http GET https://registry.npmjs.org/sourcemint-pm-git/0.1.18
npm http 304 https://registry.npmjs.org/q/0.8.2
npm http 304 https://registry.npmjs.org/wrench/1.3.8
npm http 304 https://registry.npmjs.org/n-util/0.0.1
npm http 304 https://registry.npmjs.org/glob/3.1.9
npm http 304 https://registry.npmjs.org/semver/1.0.13
npm http 304 https://registry.npmjs.org/sourcemint-pm-npm/0.1.15
npm http 304 https://registry.npmjs.org/sourcemint-pm-zip/0.1.1
npm http 304 https://registry.npmjs.org/sourcemint-pm-tar/0.1.5
npm http 304 https://registry.npmjs.org/sourcemint-pm-git/0.1.18
npm http 304 https://registry.npmjs.org/sourcemint-pm-url/0.1.1
npm http GET https://registry.npmjs.org/tar/0.1.13
npm http GET https://registry.npmjs.org/graceful-fs/1.1.8
npm http GET https://registry.npmjs.org/inherits/1.0.0
npm http GET https://registry.npmjs.org/minimatch/0.2.4
npm http GET https://registry.npmjs.org/semver/1.0.13
npm http GET https://registry.npmjs.org/event-queue/0.2.0
npm http 304 https://registry.npmjs.org/tar/0.1.13
npm http 304 https://registry.npmjs.org/event-queue/0.2.0
npm http 304 https://registry.npmjs.org/minimatch/0.2.4
npm http 304 https://registry.npmjs.org/semver/1.0.13
npm http GET https://registry.npmjs.org/block-stream/0.0.5
npm http GET https://registry.npmjs.org/fstream/0.1.18
npm http 304 https://registry.npmjs.org/inherits/1.0.0
npm http 304 https://registry.npmjs.org/graceful-fs/1.1.8
npm http GET https://registry.npmjs.org/lru-cache/1.0.6
npm http 304 https://registry.npmjs.org/block-stream/0.0.5
npm http 304 https://registry.npmjs.org/fstream/0.1.18
npm http 304 https://registry.npmjs.org/lru-cache/1.0.6
npm http GET https://registry.npmjs.org/graceful-fs/1.1.8
npm http GET https://registry.npmjs.org/mkdirp/0.3.1
npm http GET https://registry.npmjs.org/rimraf/2.0.1
npm http 304 https://registry.npmjs.org/graceful-fs/1.1.8
npm http 304 https://registry.npmjs.org/mkdirp/0.3.1
npm http 304 https://registry.npmjs.org/rimraf/2.0.1
D:\winoss\langs\nodejs\mynpm\sm -> D:\winoss\langs\nodejs\mynpm\node_modules\sm\
bin\sm

> sm@0.1.69 postinstall D:\winoss\langs\nodejs\mynpm\node_modules\sm
> node ./scripts/postinstall.js

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
TypeError: Object #<EventEmitter> has no method 'getuid'
    at Object.<anonymous> (D:\winoss\langs\nodejs\mynpm\node_modules\sm\scripts\
postinstall.js:10:59)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Array.0 (module.js:479:10)
    at EventEmitter._tickCallback (node.js:192:40)

npm ERR! sm@0.1.69 postinstall: `node ./scripts/postinstall.js`
npm ERR! `cmd "/c" "node ./scripts/postinstall.js"` failed with 1
npm ERR!
npm ERR! Failed at the sm@0.1.69 postinstall script.
npm ERR! This is most likely a problem with the sm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/postinstall.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls sm
npm ERR! There is likely additional logging output above.
npm ERR!
npm ERR! System Windows_NT 5.1.2600
npm ERR! command "D:\winoss\langs\nodejs\\node.exe" "D:\winoss\langs\nod
ejs\node_modules\npm\bin\npm-cli.js" "install" "-g" "sm"
npm ERR! cwd D:\winoss\langs\nodejs
npm ERR! node -v v0.6.15
npm ERR! npm -v 1.1.19
npm ERR! code ELIFECYCLE
npm ERR! message sm@0.1.69 postinstall: `node ./scripts/postinstall.js`
npm ERR! message `cmd "/c" "node ./scripts/postinstall.js"` failed with 1
npm ERR! errno {}
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     D:\winoss\langs\nodejs\npm-debug.log
npm not ok

D:\winoss\langs\nodejs>

**Comment by cadorn** [comment]
`sm` does not support windows at this time.

To make cloud9 installation possible on windows we will be adding a small install script to be used instead of `sm`. With that you don't get the nice features of 'sm' but at least you can run cloud9.

ETA for windows support for `sm` has not been determined but it is high on priority list.

**Comment by cadorn** [comment]
See this issue to track Cloud9 workaround: https://github.com/ajaxorg/cloud9/issues/1407

**Comment by cadorn** [comment]
To track windows support see: https://github.com/sourcemint/sm-npm/issues/6
