### ISSUE TITLE
sm doesn't work

### ISSUE THREAD

**Issue by i11v** [sourcemint/sm-npm#16]
Cannot execute sm.
Every time this error is throwing:
<code>Uncaught exception: Error: Cannot find module 'sourcemint-util-js/lib/os'</code>

**Comment by cadorn** [comment]
Are you running from source or did you install via `npm install -g sm`?

**Comment by i11v** [comment]
I'm running from source.

**Comment by cadorn** [comment]
Can you search for `sourcemint-util-js/lib/os` and tell me where it is being required?

Also make sure you are at the latest `sourcemint-util-js` source from master at: github.com/sourcemint/util-js

**Comment by i11v** [comment]
There is no any <code>os</code> folder in <code>sourcemint-util-js/lib/</code> 
<code>~/sm-npm >  ls node_modules/sourcemint-util-js/lib/
args.js            error.js           glob.js            md5.js             q.js               url-proxy-cache.js wait-for.js
console.js         fs-recursive.js    json-store.js      q-throttle.js      term.js            util.js</code>

**Comment by cadorn** [comment]
I meant a 'search in files' across the whole `sm` code tree.

**Comment by i11v** [comment]
Thank you for advice! 
I'm just install <code>sourcemint-util-js</code> and error is gone.

**Comment by cadorn** [comment]
k, great. Would still be good to know where it is being required from.

**Comment by i11v** [comment]
Sorry but I can't answer this question because I don't know :)

**Comment by i11v** [comment]
Install <code>sourcemint-util-js</code> from https://github.com/sourcemint/util-js
