### ISSUE TITLE
New post install script is failing

### ISSUE THREAD

**Issue by weissmag** [sourcemint/sm-npm#2]
After running "npm install -g sm" I get this error:
happens on windows and linux.

> sm@0.1.69 postinstall /usr/local/lib/node_modules/sm
> node ./scripts/postinstall.js

npm ERR! TypeError: options.uid should be a number
npm ERR!     at ChildProcess.spawn (child_process.js:429:26)
npm ERR!     at Object.spawn (child_process.js:342:9)
npm ERR!     at spawn (/usr/share/npm/lib/utils/exec.js:103:22)
npm ERR!     at exec (/usr/share/npm/lib/utils/exec.js:40:12)
npm ERR!     at Array.0 (/usr/share/npm/lib/utils/lifecycle.js:141:5)
npm ERR!     at EventEmitter._tickCallback (node.js:192:41)
npm ERR! You may report this log at:
npm ERR!     http://bugs.debian.org/npm
npm ERR! or use
npm ERR!     reportbug --attach /root/npm-debug.log npm
npm ERR!
npm ERR! System Linux 3.0.0-1-686-pae
npm ERR! command "node" "/usr/bin/npm" "install" "-g" "sm"
npm ERR! cwd /root
npm ERR! node -v v0.6.16
npm ERR! npm -v 1.1.4
npm ERR! message options.uid should be a number
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/npm-debug.log

Thank you 
Omer

**Comment by cadorn** [comment]
Try updating NPM to >= 1.1.16 and try installing again.

```
npm update -g npm
```

**Comment by weissmag** [comment]
this worked
apparently the debian package for node 0.6.17 (and also 0.6.18) is built without the bundled NPM so it used the old one from the npm package.
reinstalled by cloning and building myself.
thanks !

**Comment by chrismatheson** [comment]
Hi, im having the same problem but my npm version is 1.1.4 node v0.6.19 and sm 0.1.69.

Im trying to install sm on a raspberrypi (if that changes anything)

**Comment by cadorn** [comment]
I'll be releasing a new version of `sm` next week at the latest that will fail silently if the `sm` command cannot be installed. You can then manually put it on your `PATH`. This is the typical reason for install failures.

**Comment by chrismatheson** [comment]
Yeah i set up the PATH manually and the post install script worked fine. Also i installed again with node 0.8.\* and install worked first time.
