### ISSUE TITLE
Warn when `-d` is on without a directory

### ISSUE THREAD

**Issue by gjtorikian** [sourcemint/sm-npm#4]
I had mistakenly typed

`sm clone -d --dev https://github.com/ajaxorg/cloud9infra/tree/master`

The command destroyed a non-essential directory, before halting due to a permission issue. I realize one doesn't get a warning when doing, for example, `rm -rf`, but given the similarity between `-d` and `--dev`, this might be nice for fools like me. :)

**Comment by cadorn** [comment]
You are absolutely right. This is a hazard. I am removing the `-d` option so you have to use `--delete` for `>= 0.1.77`.

Thanks for reporting issues!
