### ISSUE TITLE
sm failing to install Cloud9

### ISSUE THREAD

**Issue by leeola** [sourcemint/sm-npm#5]
Ever since the new cloud9-sm switch, i've been unable to install cloud9.

When attempting to use `sm clone --dev https://github.com/ajaxorg/cloud9/tree/master cloud9`, i receive the following error..

https://gist.github.com/f16b779a903146e7c1c2
https://gist.github.com/b81f475c2dad5a9023fc
https://gist.github.com/6263c465cef198fd683d

And when cloning the cloud9 repo by hand, and then running `sm install` from inside the repo, i receive this error..

https://gist.github.com/a0dca083db9314eda53a

Note that i am using nvm, so my `which node/npm/sm` looks like this..

```
lee@work:~/projects/cloud9/cloud9$ which node
/home/lee/projects/nvm/repo/v0.6.15/bin/node
lee@work:~/projects/cloud9/cloud9$ which npm
/home/lee/projects/nvm/repo/v0.6.15/bin/npm
lee@work:~/projects/cloud9/cloud9$ which sm
/home/lee/projects/nvm/repo/v0.6.15/bin/sm
```

Any thoughts? I assume sm is having issues the sm installation? I know i tried installing sm locally to cloud9, and using it directly.. but that also failed horribly. I have yet to get sm to work :/

**Comment by cadorn** [comment]
Looks like you are getting a **ENOSPC** – _‘No space left on device’_ error which `sm` is passing through. Are you out of space or is this error incorrect?

You are on debian right? I'll see if I can do a test install on a debian system tomorrow.

**Comment by leeola** [comment]
> :(, i never even thought to check. I'm running it on a (apparently too small) virtual box, but the system updates haven't had any troubles, never thought it was a disk space issue.

I'm setting up a new box to replace this one, so i'll test it on that later today.

My apologies for not checking the npm error, and assuming it was `sm`'s fault. :/

**Comment by leeola** [comment]
At the moment i'm hung up at the following error..

https://gist.github.com/7d735a0ec944d96031a2

This is what i **originally** saw (apparently before that temporary VM got full _slaps forehead_)

**edit**: By hung up, i mean the installation has stalled and is not exiting. I'm going to give it a few more to see if it resolves..

**edit2**: We'll see if the dev version of libxml2 solves the problem, via https://github.com/ajaxorg/node-libxml/issues/3#issuecomment-4177933

**Comment by leeola** [comment]
Well i installed libxml2 dev and retried.. 

My first attempt seemed to work, as it ended with this (though.. it's a bit vague)

https://gist.github.com/9e5fb7f4c319172edf58

I then went and tried to run cloud9, and got errors involving libxml:

https://gist.github.com/029b52d7698a9803365f

I thought that this may be due to the cache, since it seems sourcemint caches in my home directory.. So i removed that and restarted the whole process.

This led me to the following output..

```

make[2]: Leaving directory `/home/lee/.sourcemint/install-cache/https/github.com/ajaxorg/jsDAV/tarball/21c6fea18d3480ef2641d9889e531ded60216082/node_modules/gnu-tools/pcre-src'
make[1]: Leaving directory `/home/lee/.sourcemint/install-cache/https/github.com/ajaxorg/jsDAV/tarball/21c6fea18d3480ef2641d9889e531ded60216082/node_modules/gnu-tools/pcre-src'
[sudo] password for lee: [3/3] cxx_link: build/Release/hosts/node-o3/sh_node_1.o build/Release/hosts/node-o3/sh_node_libs_1.o -> build/Release/o3.node
14:59:11 runner system command -> ['/usr/bin/g++', 'Release/hosts/node-o3/sh_node_1.o', 'Release/hosts/node-o3/sh_node_libs_1.o', '-o', '/home/lee/.sourcemint/install-cache/https/github.com/ajaxorg/jsDAV/tarball/21c6fea18d3480ef2641d9889e531ded60216082/node_modules/libxml/support/o3/build/Release/o3.node', '-shared', '-L/home/lee/.nvm/v0.6.15/lib', '-Wl,-Bdynamic', '-lxml2']
Waf: Leaving directory `/home/lee/.sourcemint/install-cache/https/github.com/ajaxorg/jsDAV/tarball/21c6fea18d3480ef2641d9889e531ded60216082/node_modules/libxml/support/o3/build'
'build' finished successfully (51.274s)
```

I happened to be watching the screen at the time, but it caught me off guard, because for 30 seconds or so it asked me for sudo permission. For one.. why is it doing that.. handing out sudo is not something i like to do (hell, i don't even like `npm install -g` lol).. But then after 30 seconds of displaying this odd sudo prompt, it just went on without me and now has not progressed past `'build' finished successfully (51.274s)`.

So.. thoughts?

I'll retry the whole process in a few, and edit my results back.. 

**edit**: The sudo prompt is still there, the output text just overwrite the display for a moment it seems. What does `sm` need with sudo?

**Comment by leeola** [comment]
Well, i bit the bullet and used `sudo` for some black magic code :P. Makes me rather nervous, but it worked.  So, for any future googlers, my long road of problems can be summed up with this timeline of idiocy..
- Installed sm & cloud9, ran into mystery error
- Came back later, retried and ran into the error i posted here.. turns out my VM was short on space. Yay!
- Added space, and ran into another issue. Turns out you need to install **libxml2-dev**
- `sm` seemed to have cached a bad, pre-libxml2 version, in `~/.sourcemint/`, i needed to wipe this and start over.
- `sudo` is also needed in the installation. When talking with them, it sounds like it's installing `grep`, even if you already have it..
- After that, everything is golden.

Hope my pain solves someones troubles lol, consider this issue resolved :)

**Comment by cadorn** [comment]
Good to hear you have it working!
