### ISSUE TITLE
Error installing sm with node 0.8

### ISSUE THREAD

**Issue by mattbrun** [sourcemint/sm-npm#9]
Hello,
I'm trying to install sm with node 0.8.0 on Ubuntu 11.10 64bit, and there seams to be some dependency issues. What I found is that sm try to install block-stream 0.0.5, which is not compatible with node 0.8.0. I found this dependency in npm-shrinkwrap.json (https://github.com/sourcemint/sm-npm/blob/master/npm-shrinkwrap.json).
I tried to install block-stream alone with npm, and it worked just fine (it installs the 0.06 version). After that I tried to reinstall sm, but it doesn't take the already installed block-stream.
Would it be possible to get block-stream version 0.0.6 or later?

This is the output of my installation:
$ sudo npm install -g sm
[...]
npm ERR! System Linux 3.0.0-21-generic
npm ERR! command "nodejs" "/usr/bin/npm" "install" "-g" "sm"
npm ERR! cwd /home/user1
npm ERR! node -v v0.8.0
npm ERR! npm -v 1.1.32
npm ERR! path /usr/lib/node_modules/sm/node_modules/sourcemint-pm-sm/node_modules/sourcemint-pm-tar/node_modules/tar/node_modules/fstream/fstream.js
npm ERR! code ENOENT
npm ERR! message ENOENT, open '/usr/lib/node_modules/sm/node_modules/sourcemint-pm-sm/node_modules/sourcemint-pm-tar/node_modules/tar/node_modules/fstream/fstream.js'
npm ERR! errno 34
npm ERR! 34 errno
npm ERR! notsup Unsupported
npm ERR! notsup Not compatible with your version of node/npm: block-stream@0.0.5
npm ERR! notsup Required: {"node":"0.4 || ~0.5.8 || 0.6 || 0.7"}
npm ERR! notsup Actual:   {"npm":"1.1.32","node":"0.8.0"}
[...]

Thanks for your attention,
Matteo

**Comment by kevwil** [comment]
Same issue here. The shrinkwrap file needs to be updated.

**Comment by mattbrun** [comment]
I saw you already made the pull request. Nice! :)
